# Generated by Django 6.1.1 on 2026-10-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="cover",
            new_name="profile_picture",
        ),
    ]
